version: '3.7'

services:
    backend:
        container_name: ump-api
        image: docker.pkg.github.com/webdev-studios/uitrun-be/uitrun-be:lastest
        restart: always
        volumes:
            - ump-volume:/usr/src/app
        ports:
            - 8080:8080
        env_file:
            - ./.env
        networks:
            ump-net:
        
volumes:
    uitrun-volume:
networks:
    uitrun-net:
        
